package workflow

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

// ProviderFiles returns files to commit to the provider's configured branch.
func ProviderFiles(provider string) (map[string][]byte, error) {
	name := ""
	switch provider {
	case "codemagic":
		name = "codemagic.yaml"
	case "bitrise":
		name = "bitrise.yml"
	default:
		return nil, fmt.Errorf("unknown external provider %q", provider)
	}
	yaml, err := GetTemplate(name)
	if err != nil {
		return nil, err
	}
	script, err := GetTemplate("runner.sh")
	if err != nil {
		return nil, err
	}
	return map[string][]byte{name: yaml, ".builder/ci/runner.sh": script}, nil
}

// WriteProviderFiles refuses to replace unrelated CI files and checks all
// destinations before writing any file. Existing Builder-generated files update.
func WriteProviderFiles(dir, provider string) ([]string, error) {
	root, err := filepath.Abs(dir)
	if err != nil {
		return nil, err
	}
	dir = root
	files, err := ProviderFiles(provider)
	if err != nil {
		return nil, err
	}
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		dest := filepath.Join(dir, path)
		for parent := filepath.Dir(dest); parent != root; parent = filepath.Dir(parent) {
			info, err := os.Lstat(parent)
			if os.IsNotExist(err) {
				continue
			}
			if err != nil {
				return nil, err
			}
			if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
				return nil, fmt.Errorf("refusing to write through non-directory or symlink %s", parent)
			}
		}
		info, err := os.Lstat(dest)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return nil, err
		}
		if !info.Mode().IsRegular() {
			return nil, fmt.Errorf("refusing to replace non-regular file %s", path)
		}
		data, err := os.ReadFile(dest)
		if err != nil {
			return nil, err
		}
		if !bytes.Contains(data, []byte("# Generated by ios-builder.")) {
			return nil, fmt.Errorf("%s already exists and is not generated by Builder; merge the workflow manually (see docs/providers.md)", path)
		}
	}
	for _, path := range paths {
		dest := filepath.Join(dir, path)
		if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(dest, files[path], 0644); err != nil {
			return nil, err
		}
	}
	return paths, nil
}
