package workflow

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"

	"github.com/MobAI-App/ios-builder/internal/config"
)

var (
	codemagicInstanceRe = regexp.MustCompile(`(?m)^(\s*)instance_type: ` + regexp.QuoteMeta(config.DefaultCodemagicInstance) + `$`)
	bitriseMachineRe    = regexp.MustCompile(`(?m)^(\s*)machine_type_id: ` + regexp.QuoteMeta(config.DefaultBitriseMachine) + `$`)
)

// ProviderFiles returns files to commit to the provider's configured branch,
// with the machine from ci: Codemagic instance_type, Bitrise machine_type_id
// and stack (empty keeps the template's default; no stack leaves it to the
// Bitrise app settings).
func ProviderFiles(provider string, ci config.CIConfig) (map[string][]byte, error) {
	name := ""
	switch provider {
	case "codemagic":
		name = "codemagic.yaml"
	case "bitrise":
		name = "bitrise.yml"
	default:
		return nil, fmt.Errorf("unknown external provider %q", provider)
	}
	yaml, err := GetTemplate(name)
	if err != nil {
		return nil, err
	}
	for _, f := range []struct{ field, value string }{
		{"instance_type", ci.InstanceType}, {"machine_type_id", ci.MachineTypeID}, {"stack", ci.Stack},
	} {
		if _, err := config.CheckMachine(provider, f.field, f.value); err != nil {
			return nil, err
		}
	}
	switch provider {
	case "codemagic":
		if ci.InstanceType != "" {
			yaml = codemagicInstanceRe.ReplaceAll(yaml, []byte("${1}instance_type: "+ci.InstanceType))
		}
	case "bitrise":
		machine := ci.MachineTypeID
		if machine == "" {
			machine = config.DefaultBitriseMachine
		}
		repl := "${1}machine_type_id: " + machine
		if ci.Stack != "" {
			repl += "\n${1}stack: " + ci.Stack
		}
		yaml = bitriseMachineRe.ReplaceAll(yaml, []byte(repl))
	}
	script, err := GetTemplate("runner.sh")
	if err != nil {
		return nil, err
	}
	return map[string][]byte{name: yaml, ".builder/ci/runner.sh": script}, nil
}

// WriteProviderFiles refuses to replace unrelated CI files and checks all
// destinations before writing any file. Existing Builder-generated files update.
func WriteProviderFiles(dir, provider string, ci config.CIConfig) ([]string, error) {
	root, err := filepath.Abs(dir)
	if err != nil {
		return nil, err
	}
	dir = root
	files, err := ProviderFiles(provider, ci)
	if err != nil {
		return nil, err
	}
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		dest := filepath.Join(dir, path)
		for parent := filepath.Dir(dest); parent != root; parent = filepath.Dir(parent) {
			info, err := os.Lstat(parent)
			if os.IsNotExist(err) {
				continue
			}
			if err != nil {
				return nil, err
			}
			if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
				return nil, fmt.Errorf("refusing to write through non-directory or symlink %s", parent)
			}
		}
		info, err := os.Lstat(dest)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return nil, err
		}
		if !info.Mode().IsRegular() {
			return nil, fmt.Errorf("refusing to replace non-regular file %s", path)
		}
		data, err := os.ReadFile(dest)
		if err != nil {
			return nil, err
		}
		if !bytes.Contains(data, []byte("# Generated by ios-builder.")) {
			return nil, fmt.Errorf("%s already exists and is not generated by Builder; merge the workflow manually (see docs/providers.md)", path)
		}
	}
	for _, path := range paths {
		dest := filepath.Join(dir, path)
		if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(dest, files[path], 0644); err != nil {
			return nil, err
		}
	}
	return paths, nil
}
