package main

import (
	"os"
	"testing"

	"github.com/MobAI-App/ios-builder/internal/config"
	"github.com/spf13/cobra"
)

func providerInitCommand(name string) *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Flags().String("provider", name, "")
	cmd.Flags().String("app-id", name+"-app", "")
	cmd.Flags().String("branch", "ci-main", "")
	cmd.Flags().Bool("set-default", false, "")
	return cmd
}

func TestAddingProvidersPreservesSettingsAndDefault(t *testing.T) {
	chdir(t)
	cfg := &config.Config{Project: "App", Platform: "ios", GitHub: config.GitHubConfig{Owner: "owner", Repo: "repo"}, IOS: config.IOSConfig{Signing: true, Configuration: "Release"}, Flutter: config.FlutterConfig{Version: "3.24.0"}}
	mgr := config.NewManager()
	if err := mgr.Save(cfg); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"codemagic", "bitrise"} {
		if err := runProviderInit(providerInitCommand(name)); err != nil {
			t.Fatal(err)
		}
	}
	got, err := mgr.Load()
	if err != nil {
		t.Fatal(err)
	}
	name, err := got.ProviderName("")
	if err != nil || name != "github" {
		t.Fatal("adding accounts changed default")
	}
	if got.Codemagic.AppID != "codemagic-app" || got.Bitrise.AppID != "bitrise-app" || !got.IOS.Signing || got.IOS.Configuration != "Release" || got.Flutter.Version != "3.24.0" {
		t.Fatalf("lost settings: %+v", got)
	}
	cmd := providerInitCommand("bitrise")
	if err := cmd.Flags().Set("set-default", "true"); err != nil {
		t.Fatal(err)
	}
	if err := runProviderInit(cmd); err != nil {
		t.Fatal(err)
	}
	got, err = mgr.Load()
	if err != nil || got.Provider != "bitrise" {
		t.Fatal("explicit default not saved")
	}
}

func TestReinitializingCustomProviderPreservesWorkflowsAndFiles(t *testing.T) {
	for _, name := range []string{"codemagic", "bitrise"} {
		t.Run(name, func(t *testing.T) {
			chdir(t)
			cfg := &config.Config{Project: "App", GitHub: config.GitHubConfig{Owner: "owner", Repo: "repo"}, Codemagic: config.CIConfig{AppID: "codemagic-app", Branch: "old", BuildWorkflow: "custom-build", ShareWorkflow: "custom-share"}, Bitrise: config.CIConfig{AppID: "bitrise-app", Branch: "old", BuildWorkflow: "custom-build", ShareWorkflow: "custom-share"}}
			mgr := config.NewManager()
			if err := mgr.Save(cfg); err != nil {
				t.Fatal(err)
			}
			files := []string{"codemagic.yaml", "bitrise.yml", ".builder/ci/runner.sh"}
			if err := os.MkdirAll(".builder/ci", 0755); err != nil {
				t.Fatal(err)
			}
			for _, f := range files {
				if err := os.WriteFile(f, []byte("# Generated by ios-builder.\ncustom workflows\n"), 0644); err != nil {
					t.Fatal(err)
				}
			}
			cmd := providerInitCommand(name)
			if err := cmd.Flags().Set("set-default", "true"); err != nil {
				t.Fatal(err)
			}
			if err := runProviderInit(cmd); err != nil {
				t.Fatal(err)
			}
			got, err := mgr.Load()
			if err != nil {
				t.Fatal(err)
			}
			selected, err := got.ProviderConfig(name)
			if err != nil || selected.BuildWorkflow != "custom-build" || selected.ShareWorkflow != "custom-share" || selected.Branch != "ci-main" || got.Provider != name {
				t.Fatalf("lost configuration: %+v %v", got, err)
			}
			other := got.Bitrise
			if name == "bitrise" {
				other = got.Codemagic
			}
			if other.Branch != "old" || other.BuildWorkflow != "custom-build" {
				t.Fatalf("other provider modified: %+v", other)
			}
			for _, f := range files {
				data, err := os.ReadFile(f)
				if err != nil || string(data) != "# Generated by ios-builder.\ncustom workflows\n" {
					t.Fatalf("changed %s: %q %v", f, data, err)
				}
			}
		})
	}
}
