#!/bin/bash
# Generated by ios-builder. Shared Codemagic/Bitrise runner, macOS Bash 3.2 compatible.
set -euo pipefail

ci_dir="${BUILDER_CI_DIR:-$HOME/.ios-builder-ci}"
mkdir -p "$ci_dir"
mode="${1:-build}"
export IOS_PATH="${IOS_PATH:-.}" SCHEME="${SCHEME:-}" CONFIGURATION="${CONFIGURATION:-Debug}"
export USE_SIGNING="${USE_SIGNING:-false}" JDK_VERSION="${JDK_VERSION:-17}"

snapshot_checkout() {
  case "${SNAPSHOT_REF:-}" in
    refs/ios-builder/jobs/*) ;;
    *) echo "Missing or invalid SNAPSHOT_REF" >&2; exit 1 ;;
  esac
  if ! [[ "${SNAPSHOT_SHA:-}" =~ ^[a-f0-9]{40}$ ]]; then
    echo "Missing or invalid SNAPSHOT_SHA" >&2; exit 1
  fi
  git fetch --no-tags --depth=1 origin "$SNAPSHOT_REF"
  if [ "$(git rev-parse FETCH_HEAD)" != "$SNAPSHOT_SHA" ]; then
    echo "Snapshot SHA mismatch; refusing to build different source" >&2; exit 1
  fi
  git checkout --force --detach "$SNAPSHOT_SHA"
  export BUILDER_WORKSPACE="$(pwd)"
  echo "Building snapshot $SNAPSHOT_SHA"
}

prepare() {
  if [ -f pubspec.yaml ]; then
    project_type=flutter
  elif [ -f package.json ] && grep -q '"expo"' package.json; then
    project_type=expo
  elif [ -f package.json ] && grep -q '"react-native"' package.json; then
    project_type=reactnative
  elif grep -rqlE 'kotlin\("multiplatform"\)|org\.jetbrains\.kotlin\.multiplatform|id\("org.jetbrains.kotlin.multiplatform"\)' --include='*.gradle.kts' --include='*.gradle' --include='libs.versions.toml' . 2>/dev/null; then
    project_type=kmp
  else
    project_type=native
  fi
  echo "Project type: $project_type"
  if ! command -v jq >/dev/null; then brew install jq; fi

  # Match the GitHub workflows' committed xcconfig-template convention.
  find . -path ./DerivedData -prune -o -type f \
    \( -name '*.xcconfig.template' -o -name '*.xcconfig.example' -o -name '*.xcconfig.sample' \
       -o -name '*.template.xcconfig' -o -name '*.example.xcconfig' -o -name '*.sample.xcconfig' \) -print \
  | while IFS= read -r template; do
      case "$template" in
        *.xcconfig.template|*.xcconfig.example|*.xcconfig.sample) target="${template%.*}" ;;
        *) target="$(dirname "$template")/$(basename "$template" | sed -E 's/\.(template|example|sample)\.xcconfig$/.xcconfig/')" ;;
      esac
      if [ ! -f "$target" ]; then cp "$template" "$target"; echo "Copied template to $target"; fi
    done

  if [ "$project_type" = flutter ]; then
    if [ -n "${FLUTTER_VERSION:-}" ] || ! command -v flutter >/dev/null; then
      flutter_dir="$(mktemp -d "$ci_dir/flutter.XXXXXX")"
      git clone --depth=1 --branch "${FLUTTER_VERSION:-stable}" https://github.com/flutter/flutter.git "$flutter_dir/sdk"
      export PATH="$flutter_dir/sdk/bin:$PATH"
    fi
    flutter pub get
  elif [ "$project_type" = reactnative ] || [ "$project_type" = expo ]; then
    if ! command -v node >/dev/null; then brew install node@22; export PATH="$(brew --prefix node@22)/bin:$PATH"; fi
    if [ -f yarn.lock ]; then
      if ! command -v yarn >/dev/null; then npm install -g yarn; fi
      yarn install --frozen-lockfile
    elif [ -f package-lock.json ]; then npm ci
    else npm install
    fi
    if [ "$project_type" = expo ]; then npx expo prebuild --platform ios --no-install; fi
  elif [ "$project_type" = kmp ]; then
    if ! [[ "$JDK_VERSION" =~ ^[0-9]+$ ]]; then echo "JDK_VERSION must be a major version" >&2; exit 1; fi
    if JAVA_HOME=$(/usr/libexec/java_home -v "$JDK_VERSION" 2>/dev/null); then
      export JAVA_HOME
    else
      brew install "openjdk@$JDK_VERSION"
      export JAVA_HOME="$(brew --prefix "openjdk@$JDK_VERSION")/libexec/openjdk.jdk/Contents/Home"
    fi
    export PATH="$JAVA_HOME/bin:$PATH"
    if [ -f gradlew ]; then chmod +x gradlew; fi
  fi

  cd "$BUILDER_WORKSPACE/$IOS_PATH"
  if [ -z "$(find . -maxdepth 1 -name '*.xcodeproj' -print -quit)" ]; then
    for manifest in project.yml project.yaml; do
      if [ -f "$manifest" ] && grep -qE '^targets:' "$manifest"; then
        if ! command -v xcodegen >/dev/null; then brew install xcodegen; fi
        xcodegen generate --spec "$manifest"
        break
      fi
    done
  fi
  if [ -f Podfile ]; then
    if ! command -v pod >/dev/null; then brew install cocoapods; fi
    pod install
  fi
  cd "$BUILDER_WORKSPACE"
}

select_project() {
  cd "$BUILDER_WORKSPACE/$IOS_PATH"
  workspace=$(find . -maxdepth 1 -name '*.xcworkspace' -print -quit)
  project=$(find . -maxdepth 1 -name '*.xcodeproj' -print -quit)
  if [ -n "$workspace" ]; then target=(-workspace "$workspace"); base=$(basename "$workspace" .xcworkspace)
  elif [ -n "$project" ]; then target=(-project "$project"); base=$(basename "$project" .xcodeproj)
  else echo "No Xcode project/workspace in $IOS_PATH" >&2; exit 1
  fi
  if [ -z "$SCHEME" ]; then
    if [ "$project_type" = flutter ]; then SCHEME=Runner
    else
      schemes=$(xcodebuild "${target[@]}" -list -json | jq -r '(.workspace // .project).schemes[]?')
      SCHEME=$(printf '%s\n' "$schemes" | grep -Fx "$base" || true)
      if [ -z "$SCHEME" ]; then
        while IFS= read -r candidate; do
          case "$candidate" in ''|Pods-*) continue ;; esac
          [ -z "$(find . -maxdepth 4 -path "*/$candidate/Package.swift" -print -quit)" ] || continue
          SCHEME=$candidate; break
        done <<< "$schemes"
      fi
    fi
  fi
  if [ -z "$SCHEME" ]; then echo "No app scheme found; set ios.scheme in builder.json" >&2; exit 1; fi
}

cleanup_signing() {
  if [ -n "${keychain_path:-}" ]; then security delete-keychain "$keychain_path" || true; fi
  if [ -n "${profile_dest:-}" ]; then rm -f "$profile_dest"; fi
  if [ -n "${signing_dir:-}" ]; then rm -rf "$signing_dir"; fi
}

install_signing() {
  : "${IOS_CERTIFICATE:?Set the IOS_CERTIFICATE secret on this provider}"
  : "${IOS_CERTIFICATE_PASSWORD?Set IOS_CERTIFICATE_PASSWORD on this provider (may be empty)}"
  : "${IOS_PROVISIONING_PROFILE:?Set IOS_PROVISIONING_PROFILE on this provider}"
  signing_dir=$(mktemp -d "$ci_dir/signing.XXXXXX")
  keychain_path="$signing_dir/signing.keychain-db"
  keychain_password=$(openssl rand -base64 32)
  trap cleanup_signing EXIT
  security create-keychain -p "$keychain_password" "$keychain_path"
  security set-keychain-settings -lut 7200 "$keychain_path"
  security unlock-keychain -p "$keychain_password" "$keychain_path"
  printf '%s' "$IOS_CERTIFICATE" | base64 --decode > "$signing_dir/certificate.p12"
  security import "$signing_dir/certificate.p12" -P "$IOS_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k "$keychain_path"
  security set-key-partition-list -S apple-tool:,apple: -k "$keychain_password" "$keychain_path"
  security list-keychains -d user -s "$keychain_path" "$HOME/Library/Keychains/login.keychain-db"
  printf '%s' "$IOS_PROVISIONING_PROFILE" | base64 --decode > "$signing_dir/profile.mobileprovision"
  security cms -D -i "$signing_dir/profile.mobileprovision" > "$signing_dir/profile.plist"
  profile_uuid=$(plutil -extract UUID raw -o - "$signing_dir/profile.plist")
  export DEVELOPMENT_TEAM="$(plutil -extract TeamIdentifier.0 raw -o - "$signing_dir/profile.plist")"
  export PROVISIONING_PROFILE_NAME="$(plutil -extract Name raw -o - "$signing_dir/profile.plist")"
  mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
  profile_dest="$HOME/Library/MobileDevice/Provisioning Profiles/$profile_uuid.mobileprovision"
  cp "$signing_dir/profile.mobileprovision" "$profile_dest"
}

build_ipa() {
  if [ "$project_type" = flutter ]; then
    cd "$BUILDER_WORKSPACE"
    case "$CONFIGURATION" in Debug) flutter build ios --debug --no-codesign ;; *) flutter build ios --release --no-codesign ;; esac
  fi
  select_project
  args=("${target[@]}" -scheme "$SCHEME" -configuration "$CONFIGURATION" -destination 'generic/platform=iOS'
    -derivedDataPath "$BUILDER_WORKSPACE/DerivedData" COMPILER_INDEX_STORE_ENABLE=NO)
  mkdir -p "$BUILDER_WORKSPACE/build"
  if [ "$USE_SIGNING" = true ]; then
    install_signing
    xcodebuild "${args[@]}" DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" CODE_SIGN_STYLE=Manual \
      PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME" -archivePath "$BUILDER_WORKSPACE/build/App.xcarchive" archive
    export APP_BUNDLE_ID="$(plutil -extract ApplicationProperties.CFBundleIdentifier raw -o - "$BUILDER_WORKSPACE/build/App.xcarchive/Info.plist")"
    python3 - "$signing_dir/ExportOptions.plist" <<'PY'
import os, plistlib, sys
with open(sys.argv[1], 'wb') as out:
    plistlib.dump({'method': 'development', 'signingStyle': 'manual',
                  'teamID': os.environ['DEVELOPMENT_TEAM'],
                  'provisioningProfiles': {os.environ['APP_BUNDLE_ID']: os.environ['PROVISIONING_PROFILE_NAME']}}, out)
PY
    xcodebuild -exportArchive -archivePath "$BUILDER_WORKSPACE/build/App.xcarchive" \
      -exportOptionsPlist "$signing_dir/ExportOptions.plist" -exportPath "$signing_dir/export"
    ipa=$(find "$signing_dir/export" -maxdepth 1 -name '*.ipa' -print -quit)
    test -n "$ipa"
    cp "$ipa" "$BUILDER_WORKSPACE/build/$BUILD_ID.ipa"
  else
    if [ "$project_type" = flutter ]; then
      app_path=$(find "$BUILDER_WORKSPACE/build/ios/iphoneos" -maxdepth 1 -name '*.app' -print -quit)
    else
      xcodebuild "${args[@]}" CODE_SIGNING_ALLOWED=NO build
      app_path=$(xcodebuild "${args[@]}" -showBuildSettings -json | jq -r 'map(.buildSettings) | map(select(.PRODUCT_TYPE == "com.apple.product-type.application" and (.TARGET_BUILD_DIR | contains("-iphoneos")))) | map(.TARGET_BUILD_DIR + "/" + .FULL_PRODUCT_NAME) | first // empty')
    fi
    test -d "$app_path"
    payload_dir=$(mktemp -d "$ci_dir/payload.XXXXXX")
    mkdir -p "$payload_dir/Payload"
    cp -R "$app_path" "$payload_dir/Payload/"
    (cd "$payload_dir"; zip -rq "$BUILDER_WORKSPACE/build/$BUILD_ID.ipa" Payload)
    rm -rf "$payload_dir"
  fi
  echo "Created build/$BUILD_ID.ipa"
}

build_simulator() {
  : "${MOBAI_API_KEY:?Set MOBAI_API_KEY on this provider to share a simulator}"
  if ! command -v mobai-ci >/dev/null; then
    curl -fsSL https://raw.githubusercontent.com/MobAI-App/mobai-ci/v1/install.sh -o "$ci_dir/install-mobai.sh"
    MOBAI_CI_BIN_DIR="$ci_dir/bin" sh "$ci_dir/install-mobai.sh"
    export PATH="$ci_dir/bin:$PATH"
  fi
  sim_udid=$(mobai-ci sim boot --cache "$ci_dir/sim-cache" --device-type 'iPhone 16 Pro' --runtime latest | tail -1)
  test -n "$sim_udid"
  if [ "$project_type" = flutter ]; then
    cd "$BUILDER_WORKSPACE"
    flutter build ios --simulator --debug
    app_path=$(find "$BUILDER_WORKSPACE/build/ios/iphonesimulator" -maxdepth 1 -name '*.app' -print -quit)
  else
    select_project
    args=("${target[@]}" -scheme "$SCHEME" -configuration Debug -destination "id=$sim_udid"
      -derivedDataPath "$BUILDER_WORKSPACE/DerivedData" COMPILER_INDEX_STORE_ENABLE=NO CODE_SIGNING_ALLOWED=NO)
    xcodebuild "${args[@]}" build
    app_path=$(xcodebuild "${args[@]}" -showBuildSettings -json | jq -r 'map(.buildSettings) | map(select(.PRODUCT_TYPE == "com.apple.product-type.application" and (.TARGET_BUILD_DIR | contains("-iphonesimulator")))) | map(.TARGET_BUILD_DIR + "/" + .FULL_PRODUCT_NAME) | first // empty')
  fi
  test -d "$app_path"
  printf '%s\n' "$app_path" > "$ci_dir/app-path"
  printf '%s\n' "$sim_udid" > "$ci_dir/sim-udid"
}

case "$mode" in
  checkout) snapshot_checkout ;;
  build|simulator)
    if ! [[ "${BUILD_ID:-}" =~ ^[a-f0-9]{8}$ ]]; then echo "Invalid BUILD_ID" >&2; exit 1; fi
    snapshot_checkout
    prepare
    if [ "$mode" = build ]; then build_ipa; else build_simulator; fi
    ;;
  share)
    export PATH="$ci_dir/bin:$PATH"
    exec mobai-ci share --device "$(cat "$ci_dir/sim-udid")" --app "$(cat "$ci_dir/app-path")" \
      --duration "${DURATION:-30m}" --label "${BUILDER_REPOSITORY:-Builder} · $BUILD_ID" \
      --wait-device 4m --startup-timeout 5m
    ;;
  *) echo "Unknown runner mode: $mode" >&2; exit 1 ;;
esac
